CC = g++
FLAGS = -g -std=c++2a -pedantic -Wextra -w -pipe -Werror
FILES = basics.cpp cpp_time.cpp logger.cpp logger_builder.cpp main.cpp standard_logger.cpp standard_logger_builder.cpp

run: $(FILES)
	$(CC) $(FLAGS) $(FILES) -o $@.out
