#ifndef ___CCONSTANTS___
#define ___CCONSTANTS___

#define MEMORY_ALLOCATE_EXCEPTION 5
#define SUCCESS_FUNCTION_RETURN 6
#define ARGUMENTS_EXCEPTION 8
#define FILE_INTERRACT_EXCEPTION 9
#define WRONG_INPUT_EXCEPTION 10

#define STANDART_STRING_SIZE 255
#define STANDART_ARRAY_SIZE 10
#define EQUALS 0
#define FIRST_STRING 1
#define SECOND_STRING -1

#define STANDART_EPSIOLON 1e-6

#endif
