#ifndef ___CCONSTANTS___
#define ___CCONSTANTS___

#define MEMORY_ALLOCATE_EXCEPTION 5
#define SUCCESS_FUNCTION_RETURN 6
#define ARGUMENTS_EXCEPTION 8
#define FILE_INTERRACT_EXCEPTION 9
#define WRONG_INPUT_EXCEPTION 10
#define INDEX_OUT_OF_BOUNDS_EXCEPTION 11
#define UNKNOWN_FLAG_EXCEPTION 12
#define NO_SUCH_ELEMENT_EXCEPTION 13
#define ELEMENT_EXISTS_EXCEPTION 14
#define SEMOPHORE_INTERRACT_EXCEPTION 15
#define DEVISION_BY_ZERO 16

#define STANDART_STRING_SIZE 255
#define STANDART_ARRAY_SIZE 10
#define EQUALS 0
#define FIRST_STRING 1
#define SECOND_STRING -1

#define STANDART_EPSIOLON 1e-6

#define STANDART_MAPPED_FILE_SIZE 1024

#define NEW_STRING 50
#define EXISTING_STRING 51

#endif
