CC = gcc
FLAGS = -g -std=c99 -pedantic -Wextra -w -pipe -Werror

run:
	$(CC) $(FLAGS) cexpression.c cnumber.c coverflow.c clist.c clist_int.c cstring.c main.c stack_int.c stack.c -lm -o run.out
	#$(CC) $(FLAGS) hash_table_polynomial.c hash_table.c clist.c server.c cserializer.c cstring.c coverflow.c cnumber.c -o server
